// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

var _ = templruntime.GeneratedTemplate


func main() {

	// dir, _ := os.Getwd()
	// fmt.Println("Working directory:", dir)

	fs := http.FileServer(http.Dir("./static"))
	http.Handle("/static/", http.StripPrefix("/static/", fs))

	http.HandleFunc("/", home)
	http.HandleFunc("/about", about)
	http.HandleFunc("/contact", contact)
	http.ListenAndServe(":8080", nil)

}